<a href="https://colab.research.google.com/github/MuathMohammed/DataStructureAndAlgorithms/blob/master/TaskNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# #Task 1

In [72]:
import numpy as np

In [62]:
def describe(arr):
  print('*'*10 + ' Describe The Array ' + '*'*10)
  print(f'the Dmensions: {arr.ndim}')
  print(f'the Shape: {arr.shape}')
  print(f'the Size: {arr.size}')
  print(f'the Dtype: {arr.dtype}')


In [13]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
arr = np.array((11,12,13,14,15))
print(list1,list2)
arr


[1, 2, 3, 4, 5] [6, 7, 8, 9, 10]


array([11, 12, 13, 14, 15])

In [15]:
arr2 = np.array([list1, list2], dtype=np.float64)

In [24]:
arr3 = np.ones((5,5))
arr4 = np.zeros((5,5))
arr5 = np.arange(20)
print(arr3)
print('*'*30)
print(arr4)
print('*'*30)
print(arr5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
******************************
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
******************************
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
arr6 = np.array(np.linspace(0,10,30),dtype = np.float64)

arr6

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [27]:
arr7 = np.random.rand(2,3)
arr7

array([[0.62667054, 0.07720296, 0.01807869],
       [0.43083026, 0.41353006, 0.78216179]])

In [30]:
arr8 = np.random.randint(0,30,10)
arr8

array([ 4, 11,  5, 17, 11,  9, 24, 29, 26, 12])

In [31]:
arr9 = np.random.randn(6,7)
arr9

array([[ 0.15109105, -0.87523584,  0.48526616, -0.05394774,  1.13038567,
        -0.13763399, -0.03127683],
       [-0.39453688, -1.1824488 ,  0.38219958, -1.72530664,  0.14426203,
        -0.51660948,  1.31193067],
       [-1.07868436, -1.74147332,  0.46676149,  1.04095845,  1.36140314,
        -0.1073852 , -0.18927174],
       [ 1.07064838, -0.37339106,  1.34379768, -0.82180985, -1.21407603,
         1.05786149,  0.80412474],
       [-0.38916908,  0.13113217,  2.5543241 ,  1.01786783, -1.02237068,
        -0.1031076 ,  0.20769703],
       [-0.72657894,  0.1349916 , -1.63613145, -0.43158219,  1.01685825,
         0.08655268, -1.72052717]])

In [33]:
arr10 = arr6.reshape(30)
arr10

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [35]:
arr11 = np.ones_like(arr10)
arr11   #that return ones but the same nu muber of valuse in matrix arr10

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
arr12 = np.full(shape = (2, 3, 10), fill_value= 55) # 3-demsion
arr12

array([[[55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
        [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
        [55, 55, 55, 55, 55, 55, 55, 55, 55, 55]],

       [[55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
        [55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
        [55, 55, 55, 55, 55, 55, 55, 55, 55, 55]]])

In [37]:
arr13 = np.eye(5)
arr13 # i don't know name this matrix !!

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
print(arr13)
describe(arr13)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
********** Describe The Array **********
the Dmensions: 2
the Shape: (5, 5)
the Size: 25
the Dtype: float64


# #Task 2

In [45]:
a = np.arange(1,21)
b = np.arange(20,40)

In [46]:
print('a:', a )   #1*20
print('b:', b)    #1*20

a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
b: [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [48]:
print('a + b:', a + b)
print('-'*40)



a + b: [21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59]
----------------------------------------
a - b: [-19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19
 -19 -19]
----------------------------------------
a * b: [ 20  42  66  92 120 150 182 216 252 290 330 372 416 462 510 560 612 666
 722 780]
----------------------------------------
a / b: [20.         10.5         7.33333333  5.75        4.8         4.16666667
  3.71428571  3.375       3.11111111  2.9         2.72727273  2.58333333
  2.46153846  2.35714286  2.26666667  2.1875      2.11764706  2.05555556
  2.          1.95      ]
----------------------------------------


In [49]:
print('a - b:', a - b)
print('-'*40)

a - b: [-19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19
 -19 -19]
----------------------------------------


In [50]:
print('a * b:', a * b)
print('-'*40)

a * b: [ 20  42  66  92 120 150 182 216 252 290 330 372 416 462 510 560 612 666
 722 780]
----------------------------------------


In [51]:
print('a / b:', b / a)
print('-'*40)

a / b: [20.         10.5         7.33333333  5.75        4.8         4.16666667
  3.71428571  3.375       3.11111111  2.9         2.72727273  2.58333333
  2.46153846  2.35714286  2.26666667  2.1875      2.11764706  2.05555556
  2.          1.95      ]
----------------------------------------


In [52]:
print('a + 10:', a + 10)

a + 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [53]:
print('a - 10:',a - 10)

a - 10: [-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10]


In [54]:
print('a * 10:',a * 10)

a * 10: [ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200]


In [55]:
print('a / 10:',a / 10)

a / 10: [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
 1.9 2. ]


In [56]:
print('a ** 10:',a ** 2)

a ** 10: [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400]


In [65]:
c = np.array([[1], [2], [3], [4], [5],[6],[7],[8],[9],[10],[11],[12],[13],[14],[15],[16],[17],[18],[19],[20]]) # 2-D 5 rows & 1 column

In [66]:
print(c)
print('a.c:',a.dot(c))  #  1*20 . 5*1 = 1*1

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]
a.c: [2870]


In [76]:
print('-'*40,'\nstatistics over whole array (all elements)')

print('c min', c.min())
print('c max', c.max())
print('c sum', c.sum())
print('c mean', c.mean())
#print('c mode:', c.mode[0])

---------------------------------------- 
statistics over whole array (all elements)
c min 1
c max 20
c sum 210
c mean 10.5


In [75]:
d = np.array([[10,20], [30,40], [50,60], [70,80]])
print(d)
print('d min (columns)', d.min(axis =0))
print('d min (rows)', d.min(axis =1))
print('d max (columns)', d.max(axis =0))
print('d max (rows)', d.max(axis =1))
print('d sum (columns)', d.sum(axis =0))
print('d sum (rows)', d.sum(axis =1))
print('d mean (columns)', d.mean(axis =0))
print('d mean (rows)', d.mean(axis =1))

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
d min (columns) [10 20]
d min (rows) [10 30 50 70]
d max (columns) [70 80]
d max (rows) [20 40 60 80]
d sum (columns) [160 200]
d sum (rows) [ 30  70 110 150]
d mean (columns) [40. 50.]
d mean (rows) [15. 35. 55. 75.]
